/**
 * This file is autogenerated by scripts/generateDeployedContracts.ts
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/helper/contract";

const baseDeployedContracts = {
  11155111: {
    MockUSDC: {
        address: "0x7FEc53132c406d74995FA36579681C18F1b76C9B",
        abi: [
            {
                inputs: [],
                stateMutability: "nonpayable",
                type: "constructor"
            },
            {
                inputs: [
                    {
                        internalType: "address",
                        name: "spender",
                        type: "address"
                    },
                    {
                        internalType: "uint256",
                        name: "allowance",
                        type: "uint256"
                    },
                    {
                        internalType: "uint256",
                        name: "needed",
                        type: "uint256"
                    }
                ],
                name: "ERC20InsufficientAllowance",
                type: "error"
            },
            {
                inputs: [
                    {
                        internalType: "address",
                        name: "sender",
                        type: "address"
                    },
                    {
                        internalType: "uint256",
                        name: "balance",
                        type: "uint256"
                    },
                    {
                        internalType: "uint256",
                        name: "needed",
                        type: "uint256"
                    }
                ],
                name: "ERC20InsufficientBalance",
                type: "error"
            },
            {
                inputs: [
                    {
                        internalType: "address",
                        name: "approver",
                        type: "address"
                    }
                ],
                name: "ERC20InvalidApprover",
                type: "error"
            },
            {
                inputs: [
                    {
                        internalType: "address",
                        name: "receiver",
                        type: "address"
                    }
                ],
                name: "ERC20InvalidReceiver",
                type: "error"
            },
            {
                inputs: [
                    {
                        internalType: "address",
                        name: "sender",
                        type: "address"
                    }
                ],
                name: "ERC20InvalidSender",
                type: "error"
            },
            {
                inputs: [
                    {
                        internalType: "address",
                        name: "spender",
                        type: "address"
                    }
                ],
                name: "ERC20InvalidSpender",
                type: "error"
            },
            {
                anonymous: false,
                inputs: [
                    {
                        indexed: true,
                        internalType: "address",
                        name: "owner",
                        type: "address"
                    },
                    {
                        indexed: true,
                        internalType: "address",
                        name: "spender",
                        type: "address"
                    },
                    {
                        indexed: false,
                        internalType: "uint256",
                        name: "value",
                        type: "uint256"
                    }
                ],
                name: "Approval",
                type: "event"
            },
            {
                anonymous: false,
                inputs: [
                    {
                        indexed: true,
                        internalType: "address",
                        name: "from",
                        type: "address"
                    },
                    {
                        indexed: true,
                        internalType: "address",
                        name: "to",
                        type: "address"
                    },
                    {
                        indexed: false,
                        internalType: "uint256",
                        name: "value",
                        type: "uint256"
                    }
                ],
                name: "Transfer",
                type: "event"
            },
            {
                inputs: [
                    {
                        internalType: "address",
                        name: "owner",
                        type: "address"
                    },
                    {
                        internalType: "address",
                        name: "spender",
                        type: "address"
                    }
                ],
                name: "allowance",
                outputs: [
                    {
                        internalType: "uint256",
                        name: "",
                        type: "uint256"
                    }
                ],
                stateMutability: "view",
                type: "function"
            },
            {
                inputs: [
                    {
                        internalType: "address",
                        name: "spender",
                        type: "address"
                    },
                    {
                        internalType: "uint256",
                        name: "value",
                        type: "uint256"
                    }
                ],
                name: "approve",
                outputs: [
                    {
                        internalType: "bool",
                        name: "",
                        type: "bool"
                    }
                ],
                stateMutability: "nonpayable",
                type: "function"
            },
            {
                inputs: [
                    {
                        internalType: "address",
                        name: "account",
                        type: "address"
                    }
                ],
                name: "balanceOf",
                outputs: [
                    {
                        internalType: "uint256",
                        name: "",
                        type: "uint256"
                    }
                ],
                stateMutability: "view",
                type: "function"
            },
            {
                inputs: [],
                name: "decimals",
                outputs: [
                    {
                        internalType: "uint8",
                        name: "",
                        type: "uint8"
                    }
                ],
                stateMutability: "pure",
                type: "function"
            },
            {
                inputs: [
                    {
                        internalType: "address",
                        name: "to",
                        type: "address"
                    },
                    {
                        internalType: "uint256",
                        name: "amount",
                        type: "uint256"
                    }
                ],
                name: "mint",
                outputs: [],
                stateMutability: "nonpayable",
                type: "function"
            },
            {
                inputs: [],
                name: "name",
                outputs: [
                    {
                        internalType: "string",
                        name: "",
                        type: "string"
                    }
                ],
                stateMutability: "view",
                type: "function"
            },
            {
                inputs: [],
                name: "symbol",
                outputs: [
                    {
                        internalType: "string",
                        name: "",
                        type: "string"
                    }
                ],
                stateMutability: "view",
                type: "function"
            },
            {
                inputs: [],
                name: "totalSupply",
                outputs: [
                    {
                        internalType: "uint256",
                        name: "",
                        type: "uint256"
                    }
                ],
                stateMutability: "view",
                type: "function"
            },
            {
                inputs: [
                    {
                        internalType: "address",
                        name: "to",
                        type: "address"
                    },
                    {
                        internalType: "uint256",
                        name: "value",
                        type: "uint256"
                    }
                ],
                name: "transfer",
                outputs: [
                    {
                        internalType: "bool",
                        name: "",
                        type: "bool"
                    }
                ],
                stateMutability: "nonpayable",
                type: "function"
            },
            {
                inputs: [
                    {
                        internalType: "address",
                        name: "from",
                        type: "address"
                    },
                    {
                        internalType: "address",
                        name: "to",
                        type: "address"
                    },
                    {
                        internalType: "uint256",
                        name: "value",
                        type: "uint256"
                    }
                ],
                name: "transferFrom",
                outputs: [
                    {
                        internalType: "bool",
                        name: "",
                        type: "bool"
                    }
                ],
                stateMutability: "nonpayable",
                type: "function"
            }
        ]
    },
    ConfidentialUSDC: {
        address: "0xFA64d7a4815803f118847438F58A4B569a91a2eb",
        abi: [
            {
                inputs: [
                    {
                        internalType: "address",
                        name: "usdcAddress",
                        type: "address"
                    }
                ],
                stateMutability: "nonpayable",
                type: "constructor"
            },
            {
                inputs: [
                    {
                        internalType: "uint256",
                        name: "requestId",
                        type: "uint256"
                    }
                ],
                name: "ERC7984InvalidGatewayRequest",
                type: "error"
            },
            {
                inputs: [
                    {
                        internalType: "address",
                        name: "receiver",
                        type: "address"
                    }
                ],
                name: "ERC7984InvalidReceiver",
                type: "error"
            },
            {
                inputs: [
                    {
                        internalType: "address",
                        name: "sender",
                        type: "address"
                    }
                ],
                name: "ERC7984InvalidSender",
                type: "error"
            },
            {
                inputs: [],
                name: "ERC7984TotalSupplyOverflow",
                type: "error"
            },
            {
                inputs: [
                    {
                        internalType: "address",
                        name: "caller",
                        type: "address"
                    }
                ],
                name: "ERC7984UnauthorizedCaller",
                type: "error"
            },
            {
                inputs: [
                    {
                        internalType: "address",
                        name: "holder",
                        type: "address"
                    },
                    {
                        internalType: "address",
                        name: "spender",
                        type: "address"
                    }
                ],
                name: "ERC7984UnauthorizedSpender",
                type: "error"
            },
            {
                inputs: [
                    {
                        internalType: "euint64",
                        name: "amount",
                        type: "bytes32"
                    },
                    {
                        internalType: "address",
                        name: "user",
                        type: "address"
                    }
                ],
                name: "ERC7984UnauthorizedUseOfEncryptedAmount",
                type: "error"
            },
            {
                inputs: [
                    {
                        internalType: "address",
                        name: "holder",
                        type: "address"
                    }
                ],
                name: "ERC7984ZeroBalance",
                type: "error"
            },
            {
                inputs: [],
                name: "InvalidKMSSignatures",
                type: "error"
            },
            {
                inputs: [
                    {
                        internalType: "euint64",
                        name: "amount",
                        type: "bytes32"
                    }
                ],
                name: "InvalidUnwrapRequest",
                type: "error"
            },
            {
                inputs: [
                    {
                        internalType: "uint8",
                        name: "bits",
                        type: "uint8"
                    },
                    {
                        internalType: "uint256",
                        name: "value",
                        type: "uint256"
                    }
                ],
                name: "SafeCastOverflowedUintDowncast",
                type: "error"
            },
            {
                inputs: [
                    {
                        internalType: "address",
                        name: "token",
                        type: "address"
                    }
                ],
                name: "SafeERC20FailedOperation",
                type: "error"
            },
            {
                inputs: [
                    {
                        internalType: "bytes32",
                        name: "handle",
                        type: "bytes32"
                    },
                    {
                        internalType: "address",
                        name: "sender",
                        type: "address"
                    }
                ],
                name: "SenderNotAllowedToUseHandle",
                type: "error"
            },
            {
                inputs: [],
                name: "ZamaProtocolUnsupported",
                type: "error"
            },
            {
                anonymous: false,
                inputs: [
                    {
                        indexed: true,
                        internalType: "euint64",
                        name: "encryptedAmount",
                        type: "bytes32"
                    },
                    {
                        indexed: true,
                        internalType: "address",
                        name: "requester",
                        type: "address"
                    }
                ],
                name: "AmountDiscloseRequested",
                type: "event"
            },
            {
                anonymous: false,
                inputs: [
                    {
                        indexed: true,
                        internalType: "euint64",
                        name: "encryptedAmount",
                        type: "bytes32"
                    },
                    {
                        indexed: false,
                        internalType: "uint64",
                        name: "amount",
                        type: "uint64"
                    }
                ],
                name: "AmountDisclosed",
                type: "event"
            },
            {
                anonymous: false,
                inputs: [
                    {
                        indexed: true,
                        internalType: "address",
                        name: "from",
                        type: "address"
                    },
                    {
                        indexed: true,
                        internalType: "address",
                        name: "to",
                        type: "address"
                    },
                    {
                        indexed: true,
                        internalType: "euint64",
                        name: "amount",
                        type: "bytes32"
                    }
                ],
                name: "ConfidentialTransfer",
                type: "event"
            },
            {
                anonymous: false,
                inputs: [
                    {
                        indexed: true,
                        internalType: "address",
                        name: "holder",
                        type: "address"
                    },
                    {
                        indexed: true,
                        internalType: "address",
                        name: "operator",
                        type: "address"
                    },
                    {
                        indexed: false,
                        internalType: "uint48",
                        name: "until",
                        type: "uint48"
                    }
                ],
                name: "OperatorSet",
                type: "event"
            },
            {
                anonymous: false,
                inputs: [
                    {
                        indexed: false,
                        internalType: "bytes32[]",
                        name: "handlesList",
                        type: "bytes32[]"
                    },
                    {
                        indexed: false,
                        internalType: "bytes",
                        name: "abiEncodedCleartexts",
                        type: "bytes"
                    }
                ],
                name: "PublicDecryptionVerified",
                type: "event"
            },
            {
                anonymous: false,
                inputs: [
                    {
                        indexed: true,
                        internalType: "address",
                        name: "from",
                        type: "address"
                    },
                    {
                        indexed: true,
                        internalType: "address",
                        name: "to",
                        type: "address"
                    },
                    {
                        indexed: true,
                        internalType: "uint256",
                        name: "amount",
                        type: "uint256"
                    }
                ],
                name: "USDCWrapped",
                type: "event"
            },
            {
                anonymous: false,
                inputs: [
                    {
                        indexed: true,
                        internalType: "address",
                        name: "receiver",
                        type: "address"
                    },
                    {
                        indexed: false,
                        internalType: "euint64",
                        name: "encryptedAmount",
                        type: "bytes32"
                    },
                    {
                        indexed: false,
                        internalType: "uint64",
                        name: "cleartextAmount",
                        type: "uint64"
                    }
                ],
                name: "UnwrapFinalized",
                type: "event"
            },
            {
                anonymous: false,
                inputs: [
                    {
                        indexed: true,
                        internalType: "address",
                        name: "receiver",
                        type: "address"
                    },
                    {
                        indexed: false,
                        internalType: "euint64",
                        name: "amount",
                        type: "bytes32"
                    }
                ],
                name: "UnwrapRequested",
                type: "event"
            },
            {
                inputs: [
                    {
                        internalType: "address",
                        name: "account",
                        type: "address"
                    }
                ],
                name: "confidentialBalanceOf",
                outputs: [
                    {
                        internalType: "euint64",
                        name: "",
                        type: "bytes32"
                    }
                ],
                stateMutability: "view",
                type: "function"
            },
            {
                inputs: [],
                name: "confidentialProtocolId",
                outputs: [
                    {
                        internalType: "uint256",
                        name: "",
                        type: "uint256"
                    }
                ],
                stateMutability: "view",
                type: "function"
            },
            {
                inputs: [],
                name: "confidentialTotalSupply",
                outputs: [
                    {
                        internalType: "euint64",
                        name: "",
                        type: "bytes32"
                    }
                ],
                stateMutability: "view",
                type: "function"
            },
            {
                inputs: [
                    {
                        internalType: "address",
                        name: "to",
                        type: "address"
                    },
                    {
                        internalType: "externalEuint64",
                        name: "encryptedAmount",
                        type: "bytes32"
                    },
                    {
                        internalType: "bytes",
                        name: "inputProof",
                        type: "bytes"
                    }
                ],
                name: "confidentialTransfer",
                outputs: [
                    {
                        internalType: "euint64",
                        name: "",
                        type: "bytes32"
                    }
                ],
                stateMutability: "nonpayable",
                type: "function"
            },
            {
                inputs: [
                    {
                        internalType: "address",
                        name: "to",
                        type: "address"
                    },
                    {
                        internalType: "euint64",
                        name: "amount",
                        type: "bytes32"
                    }
                ],
                name: "confidentialTransfer",
                outputs: [
                    {
                        internalType: "euint64",
                        name: "",
                        type: "bytes32"
                    }
                ],
                stateMutability: "nonpayable",
                type: "function"
            },
            {
                inputs: [
                    {
                        internalType: "address",
                        name: "to",
                        type: "address"
                    },
                    {
                        internalType: "euint64",
                        name: "amount",
                        type: "bytes32"
                    },
                    {
                        internalType: "bytes",
                        name: "data",
                        type: "bytes"
                    }
                ],
                name: "confidentialTransferAndCall",
                outputs: [
                    {
                        internalType: "euint64",
                        name: "transferred",
                        type: "bytes32"
                    }
                ],
                stateMutability: "nonpayable",
                type: "function"
            },
            {
                inputs: [
                    {
                        internalType: "address",
                        name: "to",
                        type: "address"
                    },
                    {
                        internalType: "externalEuint64",
                        name: "encryptedAmount",
                        type: "bytes32"
                    },
                    {
                        internalType: "bytes",
                        name: "inputProof",
                        type: "bytes"
                    },
                    {
                        internalType: "bytes",
                        name: "data",
                        type: "bytes"
                    }
                ],
                name: "confidentialTransferAndCall",
                outputs: [
                    {
                        internalType: "euint64",
                        name: "transferred",
                        type: "bytes32"
                    }
                ],
                stateMutability: "nonpayable",
                type: "function"
            },
            {
                inputs: [
                    {
                        internalType: "address",
                        name: "from",
                        type: "address"
                    },
                    {
                        internalType: "address",
                        name: "to",
                        type: "address"
                    },
                    {
                        internalType: "externalEuint64",
                        name: "encryptedAmount",
                        type: "bytes32"
                    },
                    {
                        internalType: "bytes",
                        name: "inputProof",
                        type: "bytes"
                    }
                ],
                name: "confidentialTransferFrom",
                outputs: [
                    {
                        internalType: "euint64",
                        name: "transferred",
                        type: "bytes32"
                    }
                ],
                stateMutability: "nonpayable",
                type: "function"
            },
            {
                inputs: [
                    {
                        internalType: "address",
                        name: "from",
                        type: "address"
                    },
                    {
                        internalType: "address",
                        name: "to",
                        type: "address"
                    },
                    {
                        internalType: "euint64",
                        name: "amount",
                        type: "bytes32"
                    }
                ],
                name: "confidentialTransferFrom",
                outputs: [
                    {
                        internalType: "euint64",
                        name: "transferred",
                        type: "bytes32"
                    }
                ],
                stateMutability: "nonpayable",
                type: "function"
            },
            {
                inputs: [
                    {
                        internalType: "address",
                        name: "from",
                        type: "address"
                    },
                    {
                        internalType: "address",
                        name: "to",
                        type: "address"
                    },
                    {
                        internalType: "externalEuint64",
                        name: "encryptedAmount",
                        type: "bytes32"
                    },
                    {
                        internalType: "bytes",
                        name: "inputProof",
                        type: "bytes"
                    },
                    {
                        internalType: "bytes",
                        name: "data",
                        type: "bytes"
                    }
                ],
                name: "confidentialTransferFromAndCall",
                outputs: [
                    {
                        internalType: "euint64",
                        name: "transferred",
                        type: "bytes32"
                    }
                ],
                stateMutability: "nonpayable",
                type: "function"
            },
            {
                inputs: [
                    {
                        internalType: "address",
                        name: "from",
                        type: "address"
                    },
                    {
                        internalType: "address",
                        name: "to",
                        type: "address"
                    },
                    {
                        internalType: "euint64",
                        name: "amount",
                        type: "bytes32"
                    },
                    {
                        internalType: "bytes",
                        name: "data",
                        type: "bytes"
                    }
                ],
                name: "confidentialTransferFromAndCall",
                outputs: [
                    {
                        internalType: "euint64",
                        name: "transferred",
                        type: "bytes32"
                    }
                ],
                stateMutability: "nonpayable",
                type: "function"
            },
            {
                inputs: [],
                name: "contractURI",
                outputs: [
                    {
                        internalType: "string",
                        name: "",
                        type: "string"
                    }
                ],
                stateMutability: "view",
                type: "function"
            },
            {
                inputs: [],
                name: "decimals",
                outputs: [
                    {
                        internalType: "uint8",
                        name: "",
                        type: "uint8"
                    }
                ],
                stateMutability: "view",
                type: "function"
            },
            {
                inputs: [
                    {
                        internalType: "euint64",
                        name: "encryptedAmount",
                        type: "bytes32"
                    },
                    {
                        internalType: "uint64",
                        name: "cleartextAmount",
                        type: "uint64"
                    },
                    {
                        internalType: "bytes",
                        name: "decryptionProof",
                        type: "bytes"
                    }
                ],
                name: "discloseEncryptedAmount",
                outputs: [],
                stateMutability: "nonpayable",
                type: "function"
            },
            {
                inputs: [
                    {
                        internalType: "euint64",
                        name: "burntAmount",
                        type: "bytes32"
                    },
                    {
                        internalType: "uint64",
                        name: "burntAmountCleartext",
                        type: "uint64"
                    },
                    {
                        internalType: "bytes",
                        name: "decryptionProof",
                        type: "bytes"
                    }
                ],
                name: "finalizeUnwrap",
                outputs: [],
                stateMutability: "nonpayable",
                type: "function"
            },
            {
                inputs: [],
                name: "inferredTotalSupply",
                outputs: [
                    {
                        internalType: "uint256",
                        name: "",
                        type: "uint256"
                    }
                ],
                stateMutability: "view",
                type: "function"
            },
            {
                inputs: [
                    {
                        internalType: "address",
                        name: "holder",
                        type: "address"
                    },
                    {
                        internalType: "address",
                        name: "spender",
                        type: "address"
                    }
                ],
                name: "isOperator",
                outputs: [
                    {
                        internalType: "bool",
                        name: "",
                        type: "bool"
                    }
                ],
                stateMutability: "view",
                type: "function"
            },
            {
                inputs: [],
                name: "maxTotalSupply",
                outputs: [
                    {
                        internalType: "uint256",
                        name: "",
                        type: "uint256"
                    }
                ],
                stateMutability: "view",
                type: "function"
            },
            {
                inputs: [],
                name: "name",
                outputs: [
                    {
                        internalType: "string",
                        name: "",
                        type: "string"
                    }
                ],
                stateMutability: "view",
                type: "function"
            },
            {
                inputs: [
                    {
                        internalType: "address",
                        name: "",
                        type: "address"
                    },
                    {
                        internalType: "address",
                        name: "from",
                        type: "address"
                    },
                    {
                        internalType: "uint256",
                        name: "amount",
                        type: "uint256"
                    },
                    {
                        internalType: "bytes",
                        name: "data",
                        type: "bytes"
                    }
                ],
                name: "onTransferReceived",
                outputs: [
                    {
                        internalType: "bytes4",
                        name: "",
                        type: "bytes4"
                    }
                ],
                stateMutability: "nonpayable",
                type: "function"
            },
            {
                inputs: [],
                name: "rate",
                outputs: [
                    {
                        internalType: "uint256",
                        name: "",
                        type: "uint256"
                    }
                ],
                stateMutability: "view",
                type: "function"
            },
            {
                inputs: [
                    {
                        internalType: "euint64",
                        name: "encryptedAmount",
                        type: "bytes32"
                    }
                ],
                name: "requestDiscloseEncryptedAmount",
                outputs: [],
                stateMutability: "nonpayable",
                type: "function"
            },
            {
                inputs: [
                    {
                        internalType: "address",
                        name: "operator",
                        type: "address"
                    },
                    {
                        internalType: "uint48",
                        name: "until",
                        type: "uint48"
                    }
                ],
                name: "setOperator",
                outputs: [],
                stateMutability: "nonpayable",
                type: "function"
            },
            {
                inputs: [
                    {
                        internalType: "bytes4",
                        name: "interfaceId",
                        type: "bytes4"
                    }
                ],
                name: "supportsInterface",
                outputs: [
                    {
                        internalType: "bool",
                        name: "",
                        type: "bool"
                    }
                ],
                stateMutability: "view",
                type: "function"
            },
            {
                inputs: [],
                name: "symbol",
                outputs: [
                    {
                        internalType: "string",
                        name: "",
                        type: "string"
                    }
                ],
                stateMutability: "view",
                type: "function"
            },
            {
                inputs: [],
                name: "underlying",
                outputs: [
                    {
                        internalType: "contract IERC20",
                        name: "",
                        type: "address"
                    }
                ],
                stateMutability: "view",
                type: "function"
            },
            {
                inputs: [
                    {
                        internalType: "address",
                        name: "from",
                        type: "address"
                    },
                    {
                        internalType: "address",
                        name: "to",
                        type: "address"
                    },
                    {
                        internalType: "externalEuint64",
                        name: "encryptedAmount",
                        type: "bytes32"
                    },
                    {
                        internalType: "bytes",
                        name: "inputProof",
                        type: "bytes"
                    }
                ],
                name: "unwrap",
                outputs: [],
                stateMutability: "nonpayable",
                type: "function"
            },
            {
                inputs: [
                    {
                        internalType: "address",
                        name: "from",
                        type: "address"
                    },
                    {
                        internalType: "address",
                        name: "to",
                        type: "address"
                    },
                    {
                        internalType: "euint64",
                        name: "amount",
                        type: "bytes32"
                    }
                ],
                name: "unwrap",
                outputs: [],
                stateMutability: "nonpayable",
                type: "function"
            },
            {
                inputs: [
                    {
                        internalType: "address",
                        name: "to",
                        type: "address"
                    },
                    {
                        internalType: "uint256",
                        name: "amount",
                        type: "uint256"
                    }
                ],
                name: "wrap",
                outputs: [],
                stateMutability: "nonpayable",
                type: "function"
            }
        ]
    },
    ConfidentialPayroll: {
        address: "0xfdc7e95d02f3E092E1CE1fAfeAc866BF757EA812",
        abi: [
            {
                inputs: [
                    {
                        internalType: "address",
                        name: "cUSDCAddress",
                        type: "address"
                    },
                    {
                        internalType: "address",
                        name: "usdcAddress",
                        type: "address"
                    }
                ],
                stateMutability: "nonpayable",
                type: "constructor"
            },
            {
                inputs: [],
                name: "BatchTooLarge",
                type: "error"
            },
            {
                inputs: [],
                name: "DuplicateEmployee",
                type: "error"
            },
            {
                inputs: [],
                name: "EmployeeNotFound",
                type: "error"
            },
            {
                inputs: [],
                name: "EnforcedPause",
                type: "error"
            },
            {
                inputs: [],
                name: "ExpectedPause",
                type: "error"
            },
            {
                inputs: [],
                name: "LengthMismatch",
                type: "error"
            },
            {
                inputs: [
                    {
                        internalType: "address",
                        name: "owner",
                        type: "address"
                    }
                ],
                name: "OwnableInvalidOwner",
                type: "error"
            },
            {
                inputs: [
                    {
                        internalType: "address",
                        name: "account",
                        type: "address"
                    }
                ],
                name: "OwnableUnauthorizedAccount",
                type: "error"
            },
            {
                inputs: [],
                name: "ReentrancyGuardReentrantCall",
                type: "error"
            },
            {
                inputs: [
                    {
                        internalType: "bytes32",
                        name: "handle",
                        type: "bytes32"
                    },
                    {
                        internalType: "address",
                        name: "sender",
                        type: "address"
                    }
                ],
                name: "SenderNotAllowedToUseHandle",
                type: "error"
            },
            {
                inputs: [],
                name: "Unauthorized",
                type: "error"
            },
            {
                inputs: [],
                name: "ZamaProtocolUnsupported",
                type: "error"
            },
            {
                inputs: [],
                name: "ZeroAddress",
                type: "error"
            },
            {
                anonymous: false,
                inputs: [
                    {
                        indexed: true,
                        internalType: "uint256",
                        name: "id",
                        type: "uint256"
                    },
                    {
                        indexed: true,
                        internalType: "address",
                        name: "wallet",
                        type: "address"
                    }
                ],
                name: "EmployeeAdded",
                type: "event"
            },
            {
                anonymous: false,
                inputs: [
                    {
                        indexed: true,
                        internalType: "uint256",
                        name: "id",
                        type: "uint256"
                    },
                    {
                        indexed: true,
                        internalType: "address",
                        name: "wallet",
                        type: "address"
                    }
                ],
                name: "EmployeeDeactivated",
                type: "event"
            },
            {
                anonymous: false,
                inputs: [
                    {
                        indexed: true,
                        internalType: "address",
                        name: "previousOwner",
                        type: "address"
                    },
                    {
                        indexed: true,
                        internalType: "address",
                        name: "newOwner",
                        type: "address"
                    }
                ],
                name: "OwnershipTransferStarted",
                type: "event"
            },
            {
                anonymous: false,
                inputs: [
                    {
                        indexed: true,
                        internalType: "address",
                        name: "previousOwner",
                        type: "address"
                    },
                    {
                        indexed: true,
                        internalType: "address",
                        name: "newOwner",
                        type: "address"
                    }
                ],
                name: "OwnershipTransferred",
                type: "event"
            },
            {
                anonymous: false,
                inputs: [
                    {
                        indexed: false,
                        internalType: "address",
                        name: "account",
                        type: "address"
                    }
                ],
                name: "Paused",
                type: "event"
            },
            {
                anonymous: false,
                inputs: [
                    {
                        indexed: true,
                        internalType: "uint256",
                        name: "id",
                        type: "uint256"
                    },
                    {
                        indexed: true,
                        internalType: "address",
                        name: "wallet",
                        type: "address"
                    }
                ],
                name: "PaymentFailed",
                type: "event"
            },
            {
                anonymous: false,
                inputs: [
                    {
                        indexed: true,
                        internalType: "uint256",
                        name: "runId",
                        type: "uint256"
                    },
                    {
                        indexed: true,
                        internalType: "uint256",
                        name: "employeeCount",
                        type: "uint256"
                    },
                    {
                        indexed: true,
                        internalType: "uint256",
                        name: "timestamp",
                        type: "uint256"
                    }
                ],
                name: "PayrollExecuted",
                type: "event"
            },
            {
                anonymous: false,
                inputs: [
                    {
                        indexed: false,
                        internalType: "address",
                        name: "account",
                        type: "address"
                    }
                ],
                name: "Unpaused",
                type: "event"
            },
            {
                inputs: [],
                name: "MAX_BATCH",
                outputs: [
                    {
                        internalType: "uint256",
                        name: "",
                        type: "uint256"
                    }
                ],
                stateMutability: "view",
                type: "function"
            },
            {
                inputs: [],
                name: "USDC",
                outputs: [
                    {
                        internalType: "contract IERC20",
                        name: "",
                        type: "address"
                    }
                ],
                stateMutability: "view",
                type: "function"
            },
            {
                inputs: [],
                name: "acceptOwnership",
                outputs: [],
                stateMutability: "nonpayable",
                type: "function"
            },
            {
                inputs: [
                    {
                        internalType: "address[]",
                        name: "wallets",
                        type: "address[]"
                    },
                    {
                        internalType: "string[]",
                        name: "names",
                        type: "string[]"
                    },
                    {
                        internalType: "string[]",
                        name: "roles",
                        type: "string[]"
                    },
                    {
                        internalType: "externalEuint64[]",
                        name: "encSalaries",
                        type: "bytes32[]"
                    },
                    {
                        internalType: "bytes[]",
                        name: "inputProofs",
                        type: "bytes[]"
                    }
                ],
                name: "batchAddEmployees",
                outputs: [],
                stateMutability: "nonpayable",
                type: "function"
            },
            {
                inputs: [],
                name: "cUSDC",
                outputs: [
                    {
                        internalType: "contract IConfidentialUSDC",
                        name: "",
                        type: "address"
                    }
                ],
                stateMutability: "view",
                type: "function"
            },
            {
                inputs: [],
                name: "confidentialProtocolId",
                outputs: [
                    {
                        internalType: "uint256",
                        name: "",
                        type: "uint256"
                    }
                ],
                stateMutability: "view",
                type: "function"
            },
            {
                inputs: [
                    {
                        internalType: "uint256",
                        name: "id",
                        type: "uint256"
                    }
                ],
                name: "deactivateEmployee",
                outputs: [],
                stateMutability: "nonpayable",
                type: "function"
            },
            {
                inputs: [
                    {
                        internalType: "uint256",
                        name: "id",
                        type: "uint256"
                    }
                ],
                name: "getEmployee",
                outputs: [
                    {
                        internalType: "address",
                        name: "wallet",
                        type: "address"
                    },
                    {
                        internalType: "string",
                        name: "name",
                        type: "string"
                    },
                    {
                        internalType: "string",
                        name: "role",
                        type: "string"
                    },
                    {
                        internalType: "bool",
                        name: "active",
                        type: "bool"
                    },
                    {
                        internalType: "uint256",
                        name: "lastPaidAt",
                        type: "uint256"
                    }
                ],
                stateMutability: "view",
                type: "function"
            },
            {
                inputs: [],
                name: "getEmployeeCount",
                outputs: [
                    {
                        internalType: "uint256",
                        name: "",
                        type: "uint256"
                    }
                ],
                stateMutability: "view",
                type: "function"
            },
            {
                inputs: [
                    {
                        internalType: "uint256",
                        name: "id",
                        type: "uint256"
                    }
                ],
                name: "getSalary",
                outputs: [
                    {
                        internalType: "euint64",
                        name: "",
                        type: "bytes32"
                    }
                ],
                stateMutability: "nonpayable",
                type: "function"
            },
            {
                inputs: [],
                name: "owner",
                outputs: [
                    {
                        internalType: "address",
                        name: "",
                        type: "address"
                    }
                ],
                stateMutability: "view",
                type: "function"
            },
            {
                inputs: [],
                name: "pause",
                outputs: [],
                stateMutability: "nonpayable",
                type: "function"
            },
            {
                inputs: [],
                name: "paused",
                outputs: [
                    {
                        internalType: "bool",
                        name: "",
                        type: "bool"
                    }
                ],
                stateMutability: "view",
                type: "function"
            },
            {
                inputs: [],
                name: "payrollRunCount",
                outputs: [
                    {
                        internalType: "uint256",
                        name: "",
                        type: "uint256"
                    }
                ],
                stateMutability: "view",
                type: "function"
            },
            {
                inputs: [],
                name: "pendingOwner",
                outputs: [
                    {
                        internalType: "address",
                        name: "",
                        type: "address"
                    }
                ],
                stateMutability: "view",
                type: "function"
            },
            {
                inputs: [],
                name: "renounceOwnership",
                outputs: [],
                stateMutability: "nonpayable",
                type: "function"
            },
            {
                inputs: [],
                name: "runPayroll",
                outputs: [],
                stateMutability: "nonpayable",
                type: "function"
            },
            {
                inputs: [
                    {
                        internalType: "address",
                        name: "newOwner",
                        type: "address"
                    }
                ],
                name: "transferOwnership",
                outputs: [],
                stateMutability: "nonpayable",
                type: "function"
            },
            {
                inputs: [],
                name: "unpause",
                outputs: [],
                stateMutability: "nonpayable",
                type: "function"
            },
            {
                inputs: [
                    {
                        internalType: "address",
                        name: "wallet",
                        type: "address"
                    }
                ],
                name: "walletToId",
                outputs: [
                    {
                        internalType: "uint256",
                        name: "id",
                        type: "uint256"
                    }
                ],
                stateMutability: "view",
                type: "function"
            }
        ]
    }
},
} as const;

const deployedContracts = {
  ...baseDeployedContracts,
  31337: baseDeployedContracts[11155111],
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
