/**
 * Reads hardhat-deploy deployment artifacts from the `deployments/` directory
 * and generates `packages/nextjs/contracts/deployedContracts.ts` for the frontend.
 *
 * Usage: npx ts-node scripts/generateDeployedContracts.ts [networkName]
 * Default networkName: sepolia
 */
import * as fs from "fs";
import * as path from "path";

const NETWORK_NAME = process.argv[2] || "sepolia";
const CHAIN_IDS: Record<string, number> = {
  hardhat: 31337,
  localhost: 31337,
  sepolia: 11155111,
};

const CONTRACT_NAMES = ["MockUSDC", "ConfidentialUSDC", "ConfidentialPayroll"];
const DEPLOYMENTS_DIR = path.resolve(__dirname, "..", "deployments", NETWORK_NAME);
const OUTPUT_PATH = path.resolve(__dirname, "..", "..", "nextjs", "contracts", "deployedContracts.ts");

type ContractInfo = { address: string; abi: unknown[] };
type ContractsByName = Record<string, ContractInfo>;
type DeployedContractsMap = Record<number, ContractsByName>;

function loadExistingDeployedContracts(outputPath: string): DeployedContractsMap {
  if (!fs.existsSync(outputPath)) {
    return {};
  }

  const source = fs.readFileSync(outputPath, "utf-8");
  const marker = "const deployedContracts =";
  const markerIndex = source.indexOf(marker);
  if (markerIndex === -1) {
    return {};
  }

  const startBrace = source.indexOf("{", markerIndex);
  const asConstIndex = source.indexOf("} as const;", startBrace);
  if (startBrace === -1 || asConstIndex === -1) {
    return {};
  }

  const objectLiteral = source.substring(startBrace, asConstIndex + 1);

  try {
    const parsed = new Function("return " + objectLiteral)() as DeployedContractsMap;
    if (parsed && typeof parsed === "object") {
      return parsed;
    }
  } catch {
    // If parsing fails, fall back to an empty map so we don't break generation.
  }

  return {};
}

function main() {
  const chainId = CHAIN_IDS[NETWORK_NAME];
  if (!chainId) {
    console.error(`Unknown network: ${NETWORK_NAME}. Known: ${Object.keys(CHAIN_IDS).join(", ")}`);
    process.exit(1);
  }

  if (!fs.existsSync(DEPLOYMENTS_DIR)) {
    console.error(`Deployments directory not found: ${DEPLOYMENTS_DIR}`);
    console.error(`Run 'npx hardhat deploy --network ${NETWORK_NAME}' first (or use a matching 'pnpm deploy:<network>' script if available).`);
    process.exit(1);
  }

  const contracts: ContractsByName = {};

  for (const name of CONTRACT_NAMES) {
    const filePath = path.join(DEPLOYMENTS_DIR, `${name}.json`);
    if (!fs.existsSync(filePath)) {
      console.error(`Deployment artifact not found: ${filePath}`);
      process.exit(1);
    }
    const data = JSON.parse(fs.readFileSync(filePath, "utf-8"));
    contracts[name] = {
      address: data.address,
      abi: data.abi,
    };
    console.log(`  ${name}: ${data.address}`);
  }

  const existingDeployedContracts = loadExistingDeployedContracts(OUTPUT_PATH);
  const mergedDeployedContracts: DeployedContractsMap = {
    ...existingDeployedContracts,
    [chainId]: contracts,
  };

  const objectLiteral = JSON.stringify(mergedDeployedContracts, null, 4).replace(/"([^"]+)":/g, "$1:");

  const output = `/**
 * This file is autogenerated by scripts/generateDeployedContracts.ts
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/helper/contract";

const deployedContracts = ${objectLiteral} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
`;

  fs.writeFileSync(OUTPUT_PATH, output);
  console.log(`\nGenerated ${OUTPUT_PATH}`);
  console.log(`  Network: ${NETWORK_NAME} (chainId: ${chainId})`);
  console.log(`  Contracts: ${CONTRACT_NAMES.join(", ")}`);
}

main();
