/**
 * Reads hardhat-deploy deployment artifacts from the `deployments/` directory
 * and generates `packages/nextjs/contracts/deployedContracts.ts` for the frontend.
 *
 * Usage: npx ts-node scripts/generateDeployedContracts.ts [networkName]
 * Default networkName: sepolia
 */
import * as fs from "fs";
import * as path from "path";

const NETWORK_NAME = process.argv[2] || "sepolia";
const CHAIN_IDS: Record<string, number> = {
  hardhat: 31337,
  localhost: 31337,
  sepolia: 11155111,
};

const CONTRACT_NAMES = ["MockUSDC", "ConfidentialUSDC", "ConfidentialPayroll"];
const DEPLOYMENTS_DIR = path.resolve(__dirname, "..", "deployments", NETWORK_NAME);
const OUTPUT_PATH = path.resolve(__dirname, "..", "..", "nextjs", "contracts", "deployedContracts.ts");

function main() {
  const chainId = CHAIN_IDS[NETWORK_NAME];
  if (!chainId) {
    console.error(`Unknown network: ${NETWORK_NAME}. Known: ${Object.keys(CHAIN_IDS).join(", ")}`);
    process.exit(1);
  }

  if (!fs.existsSync(DEPLOYMENTS_DIR)) {
    console.error(`Deployments directory not found: ${DEPLOYMENTS_DIR}`);
    console.error(`Run 'pnpm deploy:${NETWORK_NAME}' first.`);
    process.exit(1);
  }

  const contracts: Record<string, { address: string; abi: unknown[] }> = {};

  for (const name of CONTRACT_NAMES) {
    const filePath = path.join(DEPLOYMENTS_DIR, `${name}.json`);
    if (!fs.existsSync(filePath)) {
      console.error(`Deployment artifact not found: ${filePath}`);
      process.exit(1);
    }
    const data = JSON.parse(fs.readFileSync(filePath, "utf-8"));
    contracts[name] = {
      address: data.address,
      abi: data.abi,
    };
    console.log(`  ${name}: ${data.address}`);
  }

  const output = `/**
 * This file is autogenerated by scripts/generateDeployedContracts.ts
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/helper/contract";

const deployedContracts = {
  ${chainId}: ${JSON.stringify(contracts, null, 4).replace(/"([^"]+)":/g, "$1:")},
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
`;

  fs.writeFileSync(OUTPUT_PATH, output);
  console.log(`\nGenerated ${OUTPUT_PATH}`);
  console.log(`  Network: ${NETWORK_NAME} (chainId: ${chainId})`);
  console.log(`  Contracts: ${CONTRACT_NAMES.join(", ")}`);
}

main();
